### ISSUE TITLE
Position-Count in Organizer-search is sometimes off

### ISSUE THREAD

**Issue by pc-coholic** [pretix/pretix#573] opened 2017-07-26 20:47 UTC
I have seen this issue already two or three times, but never wrote down the order-number... But now I remembered ;-)

![image](https://user-images.githubusercontent.com/654548/28642803-eaa9c074-7253-11e7-8de5-66d763277d46.png)

But curious thing: The order actually only contains 3 items...

I can't put my finger on it why the count is wrong - especially since the count in the regular event-search is correct.

However I just noticed the log-entry "The order details have been modified.".

So just throwing this out without any further verification: Perhaps global order search also counts order-items that have been removed from the order?

**Comment by danlls** [comment] 2017-07-27 01:54
This is fixed in https://github.com/pretix/pretix/commit/335955820be54ab609448bec73b6c2691edd5ebb

Log-entry "The order details have been modified." happens when the payee modify the order. I've reproduced this problem by simply creating a brand new order with multiple purchases (doesn't happen when it is only 1 item purchased). 

Hence, I believe it is not caused by both global order search / order modified by payee. Probably, something to do with OrderPosition.

**Comment by raphaelm** [comment] 2017-07-27 07:09
Yep, as @danlls pointed out, the issue is fixed in the next release and it is not related to the log entries.

It is rather related to the fact that the search also searches in attendee names and (new) invoice numbers, which are 1:n relations to the order. This leads to weirdly large result sets on SQL level and here the fun begins.

**Closed by raphaelm** 2017-07-27 07:09 UTC
