### ISSUE TITLE
Update from 2024.7.1 to 2024.8.0 failed: css and js throw 404 errors (reproducible)

### ISSUE THREAD

**Issue by Wikinaut** [pretix/pretix#4437] opened 2024-08-31 23:27 UTC
### Problem and impact

Update to 2024.7.1 was succesful, but further updating to 2024.8.0 failed:

These files are resulting now in 404 errors:

![grafik](https://github.com/user-attachments/assets/18dfed0e-b806-4302-9f63-0575741e9fda)

### Steps to reproduce

```
# sudo -u pretix -s
$ source /var/pretix/venv/bin/activate
(venv)$ pip3 install -U --upgrade-strategy eager pretix gunicorn
(venv)$ python -m pretix migrate
(venv)$ python -m pretix rebuild
(venv)$ python -m pretix updateassets
# systemctl restart pretix-web pretix-worker
 ```

### Screenshots

![grafik](https://github.com/user-attachments/assets/4115c515-cea9-45c2-8813-f7ae1c00d6c2)

### Expected 

![grafik](https://github.com/user-attachments/assets/9db64ada-fc1d-4ff4-9b3c-105d74a818c7)

### Version
2024.8.0

**Comment by raphaelm** [comment] 2024-09-01 09:20
Duplicate of #4432

**Closed** 2024-09-01 09:20 UTC

**Comment by Wikinaut** [comment] 2024-09-01 10:57
@raphaelm Please can you elaborate, what users have to fix from 2024.7.1 to 2024.8.0 ? At the moment, I understand, that static files, which were generated by pretix (installation+upgrade phase), were not served. But I regard this as a `breaking change`  which should be tackled by pretix, at least as a hint in the upgrade installation manual which I strictly followed.

**Comment by raphaelm** [comment] 2024-09-01 11:13
I closed this issue because it is a full duplicate, not because it is fixed.

I agree this is a breaking change, although one that only matters when installing pretix in a different way than any of our install guides recommend. In other words, this accidentally worked before.

I'm not yet sure if we'll "fix" it in some way or if admins need to work around. Our recommended workaround would be handling this in the reverse proxy layer, as documented. Replacing gunicorn with uwsgi might also provide solutions, however uwsgi is hard to use and also kinda deprecated, so not a solution I want to screm too loudly about.
https://uwsgi-docs.readthedocs.io/en/latest/StaticFiles.html

**Comment by Wikinaut** [comment] 2024-12-11 17:20
Finally solved today, see my solution in https://github.com/pretix/pretix/issues/4432#issuecomment-2536598254 

The problems were two:

1. python3.6 was updated to python3.9, but the change had to be applied in the apache2 configuration as well
2. pretix newer than version pretix 2024.7 requires that ```/static/``` and ```/media/``` directory contents have to served directly.

The presented solution in https://github.com/pretix/pretix/issues/4432#issuecomment-2536598254 reflects both changes and make pretix working after upgrading (here) to → version 2024.11.

solved.
