### ISSUE TITLE
order_placed signal sent before OrderPositions available to Celery

### ISSUE THREAD

**Issue by thegcat** [pretix/pretix#3630] opened 2023-10-03 18:14 UTC
### Problem and impact

This is at least a behaviour change/regression (with the way we use Pretix), whether it is a bug or not is probably in the eye of the beholder.

The issue we are facing is probably related to the new locking mechanism #2408 and might be compounded by our use of a `pgbouncer` #3620, though my understanding of the issue is not yet good enough to answer this.

The issue in itself is that it seems that the `order_placed` signal is sent before either parts of the order are reified in the DB and/or are not yet committed and thus not available outside of the transaction they were created in. (if I understand correctly this was also discussed in #2408)

We use 2 plugins that essentially [chuck some API calls to an async task](https://gitlab.fachschaften.org/kif/pretix-matrix-inviter/-/blob/main/pretix_matrix_inviter/signals.py?ref_type=heads#L70-102), and currently when the background worker works those [tasks](https://gitlab.fachschaften.org/kif/pretix-matrix-inviter/-/blob/main/pretix_matrix_inviter/tasks.py?ref_type=heads#L14) off it fails because it can't find some objects (`OrderPositions` in this case):

```
Oct 02 09:35:56 pretix celery[2516]: [2023-10-02 09:35:56,885: ERROR/ForkPoolWorker-404] Task pretix_matrix_inviter.tasks.matrix_inviter_invite[3965a3fa-90f7-4530-98b7-3bf03a0e7e7f] raised unexpected: DoesNotExist('OrderPosition matching query does not exist.')
Oct 02 09:35:56 pretix celery[2516]: Traceback (most recent call last):
Oct 02 09:35:56 pretix celery[2516]:   File "/var/pretix/venv/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
Oct 02 09:35:56 pretix celery[2516]:     R = retval = fun(*args, **kwargs)
Oct 02 09:35:56 pretix celery[2516]:   File "/var/pretix/venv/lib/python3.10/site-packages/pretix/base/services/tasks.py", line 62, in __call__
Oct 02 09:35:56 pretix celery[2516]:     ret = super().__call__(*args, **kwargs)
Oct 02 09:35:56 pretix celery[2516]:   File "/var/pretix/venv/lib/python3.10/site-packages/pretix/base/services/tasks.py", line 108, in __call__
Oct 02 09:35:56 pretix celery[2516]:     ret = super().__call__(*args, **kwargs)
Oct 02 09:35:56 pretix celery[2516]:   File "/var/pretix/venv/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
Oct 02 09:35:56 pretix celery[2516]:     return self.run(*args, **kwargs)
Oct 02 09:35:56 pretix celery[2516]:   File "/var/pretix/venv/lib/python3.10/site-packages/pretix_matrix_inviter/tasks.py", line 29, in matrix_inviter_invite
Oct 02 09:35:56 pretix celery[2516]:     order_position = OrderPosition.objects.get(pk=order_position)
Oct 02 09:35:56 pretix celery[2516]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
Oct 02 09:35:56 pretix celery[2516]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Oct 02 09:35:56 pretix celery[2516]:   File "/var/pretix/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get
Oct 02 09:35:56 pretix celery[2516]:     raise self.model.DoesNotExist(
Oct 02 09:35:56 pretix celery[2516]: pretix.base.models.orders.OrderPosition.DoesNotExist: OrderPosition matching query does not exist.
```

(some interaction with `django_scopes` might also be involved?)

Any pointers on how to better analyse the problem? Is there any signal we could use that runs after everything is committed to the DB? If possible I'd rather not add a delay or retry the taks if the objects are not there yet or something like that.v

### Version

2023.8.0

**Comment by raphaelm** [comment] 2023-10-04 07:52
This is a general issue with celery and transactions and neither caused by the new locking, nor pgbouncer, nor by django-scopes. What happens is rather simple: The celery task is queued before the transcation is committed, and because your system is idle it is also picked up by a worker before the transaction is committed. I can't rule out that some change in #2048 made this worse, but the general and best fix is to replace `base=ProfiledEventTask` with  `base=TransactionAwareProfiledEventTask` which will move the queuing after the commit of the current transaction.

**Closed by raphaelm** 2023-10-04 07:52 UTC

**Comment by thegcat** [comment] 2023-10-04 08:01
> I can't rule out that some change in #2048 made this worse,

Well, our logs didn't show this at all before the update and for at least half the cases after, so there's something. Anyways :-)

> but the general and best fix is to replace `base=ProfiledEventTask` with `base=TransactionAwareProfiledEventTask` which will move the queuing after the commit of the current transaction.

Thanks, we will try this. Should the `TransactionAware` variant be generally used, i.e. also for the other signals (`order_canceled` and `order_expired` and so on)? Is there any downside to this variant (some more in-request computation leading to longer requests or the like)?

**Comment by raphaelm** [comment] 2023-10-04 08:16
I'd prefer the transaction aware variant for most tasks
