### ISSUE TITLE
django.db.utils.NotSupportedError: URIs not supported

### ISSUE THREAD

**Issue by Pokerkoffer** [pretix/pretix#1155] opened 2019-01-31 15:03 UTC
Hi there,
the following error occurs when executing `python src/manage.py migrate` on `Pretix v2.3.0` 

```bash
$ sqlite3 --version
3.18.0 2017-03-28 18:48:43 424a0d380332858ee55bdebc4af3789f74e70a2b3ba1cf29d84b9b4bcf3e2e37

$ python -V   
Python 3.6.7

$ python -c "import sqlite3; print(sqlite3.version)"   
2.6.0

$ python -c "import sqlite3; print(sqlite3.sqlite_version)"
3.18.0
```

**.pretix.cfg:**
```
[database]
backend=sqlite3
```
**Error:**
```bash
$ python src/manage.py migrate
Traceback (most recent call last):
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 160, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.NotSupportedError: URIs not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/pretix/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/pretix/venv/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/pretix/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 82, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/pretix/venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 160, in get_new_connection
    conn = Database.connect(**conn_params)
django.db.utils.NotSupportedError: URIs not supported
```

**Comment by raphaelm** [comment] 2019-01-31 15:21
Can you post your full ``pretix.cfg``? I'm 99% sure that the error is there.

**Comment by raphaelm** [comment] 2019-01-31 15:22
Also, can you check if the ``DATA_DIR`` environment variable might be set to an URL? (It should not be set or set to a filesystem path)

**Comment by Pokerkoffer** [comment] 2019-01-31 15:23
> Can you post your full `pretix.cfg`? I'm 99% sure that the error is there.

```
pretix]
instance_name=Mah Instance Name
url=https://my.url.de
currency=EUR
datadir=/home/pretix/data_dir

[database]
backend=sqlite3

[mail]
from=mail@host.de
host=127.0.0.1
```

**Comment by Pokerkoffer** [comment] 2019-01-31 15:39
I just noticed that i had cloned master. I am currently testing with checked out v2.3.0

**Comment by raphaelm** [comment] 2019-01-31 15:52
Weird. Can you try what happens if you either omit the database block from the configuration (SQLite is default anyways) or (just for testing) do not set ``datadir``?

**Comment by Pokerkoffer** [comment] 2019-01-31 15:58
Both changes don't solve the problem, the error stays the same.

This is the conn_params obj in `venv/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py"`
```python
{
  'database': '/home/pretix/data/db.sqlite3', 
  'detect_types': 3, 
  'check_same_thread': False, 
  'uri': True
}
```

**Comment by raphaelm** [comment] 2019-01-31 15:59
Weird, seems to be that ``uri: True``, I guess. Can you show me the output of ``pip freeze``?

**Comment by Pokerkoffer** [comment] 2019-01-31 16:00
Well ok, when i set URI: False in the method above it works.

**Comment by Pokerkoffer** [comment] 2019-01-31 16:02
```bash
(venv) $:pretix $ pip freeze
amqp==2.4.0
asn1crypto==0.24.0
Babel==2.6.0
beautifulsoup4==4.7.1
billiard==3.5.0.5
bleach==2.1.4
celery==4.1.1
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.5
csscompressor==0.9.5
cssutils==1.0.2
defusedcsv==1.0.1
dj-static==0.0.6
Django==2.1.5
django-appconf==1.0.2
django-bootstrap3==10.0.1
django-compat==1.0.15
django-compressor==2.2
django-countries==5.3.2
django-filter==2.0.0
django-formset-js-improved==0.5.0.2
django-formtools==2.1
django-hierarkey==1.0.3
django-hijack==2.1.10
django-i18nfield==1.4.0
django-jquery-js==3.1.1
django-jsonfallback==2.1.0
django-libsass==0.7
django-localflavor==2.1
django-markup==1.3
django-mysql==2.4.1
django-oauth-toolkit==1.2.0
django-otp==0.4.3
django-redis==4.8.0
django-statici18n==1.8.2
djangorestframework==3.8.2
et-xmlfile==1.0.1
gunicorn==19.9.0
html5lib==1.0.1
idna==2.6
inlinestyler==0.2.5
jdcal==1.4
kombu==4.2.2.post1
libsass==0.17.0
lxml==4.3.0
Markdown==2.2.0
mt-940==3.2
oauthlib==3.0.1
openpyxl==2.5.14
paypalrestsdk==1.13.1
Pillow==5.4.1
ply==3.11
psycopg2-binary==2.7.7
pycountry==18.12.8
pycparser==2.13
pyOpenSSL==19.0.0
PyPDF2==1.26.0
python-dateutil==2.7.5
python-u2flib-server==4.0.1
pytz==2018.9
pyuca==1.2
PyYAML==3.13
raven==6.10.0
rcssmin==1.0.6
redis==2.10.5
reportlab==3.5.13
requests==2.21.0
rjsmin==1.0.12
six==1.12.0
slimit==0.8.1
soupsieve==1.7.3
static3==0.7.0
stripe==2.0.3
urllib3==1.24.1
vat-moss==0.11.0
vine==1.2.0
vobject==0.9.6.1
webencodings==0.5.1
```

**Comment by raphaelm** [comment] 2019-01-31 16:12
The ``uri: True`` is set explicitly by Django. I'm gonna close this here since it is definitively not a bug in pretix. There's an issue in Django, that itself suggests that your version of sqlite might be too old: https://code.djangoproject.com/ticket/28376

**Closed by raphaelm** 2019-01-31 16:12 UTC
Labels: question

**Comment by Pokerkoffer** [comment] 2019-01-31 16:14
> The `uri: True` is set explicitly by Django. I'm gonna close this here since it is definitively not a bug in pretix. There's an issue in Django, that itself suggests that your version of sqlite might be too old: https://code.djangoproject.com/ticket/28376

I've seen that ticket as well, but as you can see above, my currently installed sqlite version is supported. Well nevermind, maybe this is useful for someone else who gets the same error. Thanks for the help!
