### ISSUE TITLE
Selecting "flexible price" for a product negates any discount given with vouchers

### ISSUE THREAD

**Issue by MaxRink** [pretix/pretix#903] opened 2018-05-10 18:29 UTC
Our current Situation: 
we have a ticet in the shop which has three subversions. As soon as flexible pricing for the product is enabled, none of the discount options vouchers give you apply. Neither setting the price to a fixed value for the voucher nor entering a %-discount works.
As soon as flexible pricing gets turned off the vouchers apply as expected.
This happens for us on v1.15.0, propably on older versions as well ( i havent checked)
It also only happens if you have multiple versions enabled and for sale, if i create a single Ticket with flexible pricing the vouchers work.

**Comment by raphaelm** [comment] 2018-05-11 10:56
I cannot reproduce this on master right now and I don't see what changed since v1.15 that could have "fixed" this
![2018-05-11-125504_1216x388_scrot](https://user-images.githubusercontent.com/64280/39921280-958bad00-551a-11e8-8b03-3d2f0fd1f697.png)
![2018-05-11-125513_1167x119_scrot](https://user-images.githubusercontent.com/64280/39921281-95a669a6-551a-11e8-96a5-c1355d2d22d6.png)

**Comment by MaxRink** [comment] 2018-05-11 11:32
It only applies to Tickets with variations. A normal flexible price ticket works as expected
![image](https://user-images.githubusercontent.com/4894735/39922517-bf7914e0-551f-11e8-9206-e0ec58397f5a.png)
Thats the ticketsetup ive discovered the bug with.

**Comment by raphaelm** [comment] 2018-05-11 11:50
Sorry, I missed that. However, I still cannot reproduce it with variations. Can you show me the full settings of the voucher you're using?

**Comment by raphaelm** [comment] 2018-05-11 12:02
Ah another question: Does ist just *show* wrong or does it also use the wrong price when you add it to the cart?

**Comment by MaxRink** [comment] 2018-05-11 12:13
Its the wrong price even within the shoppingcart
Ticketsettings:
![image](https://user-images.githubusercontent.com/4894735/39923707-15ac0dae-5525-11e8-931d-faa75c0622a5.png)
![image](https://user-images.githubusercontent.com/4894735/39923718-1f942752-5525-11e8-8d5e-7a94112a0e0e.png)
Vouchersettings: 
![image](https://user-images.githubusercontent.com/4894735/39923755-3ada6db4-5525-11e8-96e6-77bb532cd984.png)
Redemption: 
![image](https://user-images.githubusercontent.com/4894735/39923765-5305492c-5525-11e8-9dde-490295a0fdfc.png)
Cart: 
![image](https://user-images.githubusercontent.com/4894735/39923775-616603d0-5525-11e8-9019-40c977fa3132.png)

**Comment by raphaelm** [comment] 2018-05-11 12:34
Ah. The bug in fact only occurs when the resulting price is 0, that's why I didn't get it in my tests. Fixed now in 1ee584c5, I'll try to get a bugfix release out soon.

**Closed by raphaelm** 2018-05-11 12:34 UTC
Labels: bug, pretix.presale

**Comment by raphaelm** [comment] 2018-05-11 12:54
1.15.1 is now on PyPI and on docker hub in a few hours
