### ISSUE TITLE
Sometimes wrong pdf file size calculated before sending e-mail

### ISSUE THREAD

**Issue by TimmThaler** [pretix/pretix#1387] opened 2019-09-08 10:24 UTC
I sometimes have the issue that the size of the pdf file with all tickets per order, which should be mailed to the customer, is not calculated correctly.

I just had one order, where the calculated file size by pretix is 4218802 bytes, but my computer says 1108842 bytes.
At another one there was 8438290 calculated instead of something like 2218394.

**Comment by raphaelm** [comment] 2019-09-08 18:55
Resolved via email, not a bug (the passbook files were not taken into account) :)

**Closed** 2019-09-08 18:55 UTC
