### ISSUE TITLE
Cannot change month in the widget

### ISSUE THREAD

**Issue by cesarbtt** [pretix/pretix#2438] opened 2022-01-31 13:47 UTC
In the current version it is not possible to change the month in the widget. When you hit it, it reloads but does nothing. The cause seems to be because the call https://XXXXX/widget/product_list?lang=es&year=2022&month=03 always returns the same regardless of the value you put in the month parameter.

**Comment by raphaelm** [comment] 2022-01-31 14:29
Which version of pretix are you using exactly? Is the widget embedded on a public page we might have a look at? Can you try to clear your browser cache?

Unless we missed an edge case, this should already be fixed by https://github.com/pretix/pretix/commit/c8a830ecde186e7fe8862bda1410852de50e571b

**Comment by cesarbtt** [comment] 2022-02-01 07:15
I have installed 4.6.0 version. I tried in Edge, Chrome and Firefox and in two different computers and phones.

**Comment by cesarbtt** [comment] 2022-02-01 07:15
You can view a example in  https://www.coruna.gal/bibliotecas/gl/actividades/persoais/actividades-nas-bibliotecas/detalle-evento/merendas-con-contos-as-illas-do-tesouro/suceso/1453776890580

**Comment by wiffbi** [comment] 2022-02-01 08:25
I can confirm this is due to an old version of widget.js here, which uses month/week-GET-params instead of the newly introduced, normalized single date-GET-param – see method `reload` here: https://ticketing.coruna.gal/widget/v1.es.js

Have you made sure to update styles and scripts when installing 4.6.0? Calling `python -m pretix updatestyles` should do the trick.

**Comment by cesarbtt** [comment] 2022-02-01 12:11
It's works! Thanks a lot

**Comment by kciy** [comment] 2022-03-15 22:45
I have the same problem on https://freiburg.esn-germany.de/events. Can't seem to change months, but I am loading the scripts https://pretix.eu/widget/v1.en.js and https://pretix.eu/demo/democon/widget/v1.css

**Comment by wiffbi** [comment] 2022-03-16 08:40
I am looking into this. There seems to be an issue with parsing the date.

**Closed** 2022-03-16 13:15 UTC

**Comment by kciy** [comment] 2022-03-16 14:02
Still not working on the mentioned website, or do I need to update anything?

**Comment by wiffbi** [comment] 2022-03-16 14:40
If the website is on pretix Hosted (I could not find it there), please contact our support via email. If you host pretix yourself, you need to update pretix – usually that means to wait for the next release end of this month.

In the meantime, if you self-host and do not want to or cannot wait for the next release, check the version of python-dateutil – I have python-dateutil 2.8.2 on Python 3.9.7 and it ran the old code with `parse` flawlessly, but maybe older versions stumble upon parsing a YYYY-MM date.
