### ISSUE TITLE
Further restrict access to 2FA settings

### ISSUE THREAD

**Issue by tabascoeye** [pretix/pretix#787] opened 2018-02-26 15:06 UTC
1. after registering a new device, the 2fa is still not active, which was confusing to me. I would automatically activate it after the first device was registered successfully (imho)
2. logged-in session can deactivate 2fa without being asked for any credentials or a current 2fa token
3. logged-in session can delete an associated 2fa device without being asked for any credentials or current 2fa token
4. logged-in session can view/change emergency 2fa tokens without being asked for any credentials

**Comment by tabascoeye** [comment] 2018-02-26 16:53
I just saw that each change of the profile leads to a (warning) mail being sent. Thats good, but imho not enough.

**Comment by raphaelm** [comment] 2018-03-16 12:41
Hi,

sorry for replying this late.

> after registering a new device, the 2fa is still not active, which was confusing to me. I would automatically activate it after the first device was registered successfully (imho)

This was intended, in order to prevent people locking themselves out accidentally, but Is ee why it is confusing.

> logged-in session can deactivate 2fa without being asked for any credentials or a current 2fa token
> logged-in session can delete an associated 2fa device without being asked for any credentials or current 2fa token
> logged-in session can view/change emergency 2fa tokens without being asked for any credentials

Yes, but they're all only possible if you entered your password within the last hour, otherwise you'll be prompted for your password, which is a fair trade-off I guess. But we could think about always requiring at least the password there.

**Comment by raphaelm** [comment] 2018-04-09 16:48
1. is now fixed :)

**Closed** 2021-10-31 17:05 UTC
Labels: enhancement, wontfix, pretix.control
