### ISSUE TITLE
Badges plugin generates blank pages

### ISSUE THREAD

**Issue by v0tti** [pretix/pretix#1332] opened 2019-07-05 08:52 UTC
I created my own badge layout, however sometimes when exporting a single badge PDF (from an order page) the PDF has a leading OR trailing blank page (just the background image is shown). It does not generate any blank pages when exporting all badges at a time.

**Comment by v0tti** [comment] 2019-07-05 08:53
For reference, this is the background file I am using: [badge_back.pdf](https://github.com/pretix/pretix/files/3361871/badge_back.pdf)

**Comment by raphaelm** [comment] 2019-07-05 09:13
By *sometimes*, you mean that it even occurs non-deterministically for a single given order?

**Comment by v0tti** [comment] 2019-07-05 09:17
No, for the same order it seems to occur every time, but I could not determine a reason for it. It does not seem to correlate with e.g. length of name.

This is my layout:
`[{"type":"textarea","left":"1.71","bottom":"-0.34","fontsize":"19.8","color":[0,0,0,1],"fontfamily":"Open Sans","bold":true,"italic":false,"width":"52.88","content":"attendee_name","text":"Max Mustermann","align":"center"},{"type":"textarea","left":"22.64","bottom":"18.05","fontsize":"11.8","color":[0,0,0,1],"fontfamily":"Open Sans","bold":false,"italic":true,"width":"30.75","content":"question_16","text":"<Antwort: Wähle weise!>","align":"right"}]`

**Comment by v0tti** [comment] 2019-07-05 09:21
[This is one of the affected orders.](https://github.com/pretix/pretix/files/3361980/84901cc6-907c-480b-a3f8-5b73c275a094.pdf)

**Comment by v0tti** [comment] 2019-07-06 07:31
I found out that this is happening because pretix will not only print badges for tickets that allow entrance, but also for additional articles. This was not immediately obvious and could be fixed with a simple setting. Sorry for reporting this as a bug.

**Comment by raphaelm** [comment] 2021-10-31 17:13
Closing since we could never reproduce it

**Closed by raphaelm** 2021-10-31 17:13 UTC
