### ISSUE TITLE
Merging orders / Allow customer to add positions to a submitted order

### ISSUE THREAD

**Issue by r-dannhauer** [pretix/pretix#1281] opened 2019-05-10 23:14 UTC
I have the scenario where someone buys tickets for a whole group, but they want Shirts/Merch later on, that is being sold via Pretix. The problem is, that when they want to add a shirt they have to make a new order.
To make things smooth for Checkin it would be nice to merge those two orders together.

**Comment by raphaelm** [comment] 2019-05-12 09:54
I'm sorry, we really recommend creating new orders here. Changing orders after the fact this way just makes payment processes much more complicated (for users to understand!) and can lead to unwanted situations, e.g. someone losing their ticket because they don't pay their merch in time.

That said, I think we can consider it a duplicate of #1271.

**Closed by raphaelm** 2019-05-12 09:54 UTC
