### ISSUE TITLE
Multiple standard badge layouts when cloning an event

### ISSUE THREAD

**Issue by lumsel-lt** [pretix/pretix#2540] opened 2022-03-16 18:38 UTC
**Describe the bug**
When cloning an event the standard badge layout is getting duplicated and is also set as standard. This leads to not being able to access orders due to the error stated below.

```
pretix.plugins.badges.models.BadgeLayout.MultipleObjectsReturned: get() returned more than one BadgeLayout -- it returned 2!
```

**Expected behavior**
The standard badge layout should not be copied. Furthermore the copies should not have the standard tag applied.

**Screenshots**
![image](https://user-images.githubusercontent.com/50259752/158662640-e17d9cc8-7e9b-46c0-ab93-6e98a567a8b5.png)

**Comment by raphaelm** [comment] 2022-03-16 19:03
duplicate of #2496

**Closed by raphaelm** 2022-03-16 19:03 UTC
