### ISSUE TITLE
pytz deprecation warning from dependency vobject

### ISSUE THREAD

**Issue by ethrgeist** [pretix/pretix#3751] opened 2023-11-30 10:31 UTC
### Problem and impact

Log entry shows:

```
/usr/local/lib/python3.11/site-packages/vobject/icalendar.py:341: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if hasattr(tzinfo, 'zone'):
/usr/local/lib/python3.11/site-packages/vobject/icalendar.py:342: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return toUnicode(tzinfo.zone)
/usr/local/lib/python3.11/site-packages/vobject/icalendar.py:1744: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
return tzinfo.localize(datetime.datetime(year, month, day, hour, minute, second))
```

There are 3 issues with this [file](https://github.com/eventable/vobject/blob/master/vobject/icalendar.py), it does not look like [eventable/vobject](https://github.com/eventable/vobject/) is [maintained any more](https://github.com/eventable/vobject/issues/185)

### Expected behaviour

Unsure, either the project needs a fork to atleast migrate the Pytz changes, or Pretix needs a replacement for this library.

### Version

2023.9.0

**Comment by ethrgeist** [comment] 2023-11-30 10:46
cc: https://github.com/pretix/pretix/issues/2428

**Comment by raphaelm** [comment] 2023-11-30 12:53
Yes, this is a duplicate of #2428

**Closed by raphaelm** 2023-11-30 12:53 UTC
