### ISSUE TITLE
Cannot login in control: TypeError at /control/ process() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by FlaviaBastos** [pretix/pretix#259] opened 2016-10-04 17:39 UTC
This is on a fresh clone/install on mac os x el capitan (v 10.11.6), running python 3.4, following all the steps outlined in docs (https://docs.pretix.eu/en/latest/development/setup.html)

- run `python manage.py runserver`
- access: http://localhost:8000/control/ (same result with http://localhost:8000/mrmcd/2015/)
- login

After login page, I get:
`TypeError at /control/
process() takes 2 positional arguments but 3 were given
Request Method:	GET
Request URL:	http://localhost:8000/control/
Django Version:	1.10.2
Exception Type:	TypeError
Exception Value:	
process() takes 2 positional arguments but 3 were given
Exception Location:	/Users/iMac/Progs/test_pretix/pretix/env/lib/python3.4/site-packages/sqlparse/engine/__init__.py in run, line 44
Python Executable:	/Users/iMac/Progs/test_pretix/pretix/env/bin/python
Python Version:	3.4.4
Python Path:	
['/Users/iMac/Progs/test_pretix/pretix/src',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python34.zip',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin',
 '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload',
 '/Users/iMac/Progs/test_pretix/pretix/env/lib/python3.4/site-packages',
 '/Users/iMac/Progs/test_pretix/pretix/src']
Server time:	Tue, 4 Oct 2016 17:26:53 +0000
`

I can provide more info if required.

**Comment by rixx** [comment] 2016-10-04 17:58
I cannot reproduce this with python3.5 or python3.4 - after running `python manage.py migrate`, a normal login page shows. http://localhost:8000/control/ redirects to http://localhost:8000/control/login?next=/control/

**Comment by FlaviaBastos** [comment] 2016-10-04 18:14
Hi @rixx 👋 
Hmm... I did run migrate also... 😕 
Wait, did you try to login? Because I also get the login page fine. The issue is when it tries to authenticate user. 
If you can login fine, I guess I will try on python3.5

**Comment by rixx** [comment] 2016-10-04 18:24
Ohh, I missed that!

The problem exists on clean installs of both python3.4 and python3.5.

**Comment by rixx** [comment] 2016-10-04 18:34
It's a development-only issue resulting from a incompatibility of django-debugtoolbar with sqlparse in a certain version as detailed in jazzband/django-debug-toolbar#862, except that the issue is solved by upgrading sqlparse to 0.2.1 (and probably higher version, but I submitted a pinned version for now).

You might just want to run `pip install --upgrade sqlparse` locally until the PR is merged (or @raphaelm does something similar to the PR).

**Comment by FlaviaBastos** [comment] 2016-10-04 18:55
yup! Upgrading sqlparse fixed it here too! :tada: 
Thank you!

**Closed** 2016-10-05 07:31 UTC

**Comment by mmmchl** [comment] 2017-11-07 09:13
@rixx 

Thank you for You might just want to run pip install --upgrade sqlparse 

Have a nice day
