### ISSUE TITLE
Widget "preseeds" wrong value into price field

### ISSUE THREAD

**Issue by MaxRink** [pretix/pretix#1279] opened 2019-05-10 10:53 UTC
The Pretix Widget seeds the wrong value into the price filed if you enable variable pricing.

````html
<input type="number" placeholder="0" min="45,00" name="price_6" step="any" class="pretix-widget-pricebox-price-input">
````

is the issue, where placehoulder should not be 0.

This can be observed at chaos-party-ulm.de

**Comment by pc-coholic** [comment] 2019-05-10 11:23
I tried to recreate this with the latest pretix 2.7.0 release and was not able to reproduce this issue...

Would you mind checking which version of pretix you are running?

**Comment by MaxRink** [comment] 2019-05-10 11:59
Im running 2.7.0 in the official docker container

**Comment by raphaelm** [comment] 2019-05-14 07:08
The error only occured in German locale (a decimal comma versus decimal point thing) and will be fixed in 2.7.1. Thanks for reporting!

**Closed** 2019-05-14 07:09 UTC
Labels: bug, pretix.presale, ui/ux
